export default {
  usernameInput: 'input[name="username"]',
  passwordInput: 'input[name="password"]',
  logInButton: 'input[value="Log In"]',
  registerButton: 'a[href^="register.htm"]',
  firstName: "#customer\\.firstName",
  lastName: "#customer\\.lastName",
  address: "#customer\\.address\\.street",
  city: "#customer\\.address\\.city",
  state: "#customer\\.address\\.state",
  zipCode: "#customer\\.address\\.zipCode",
  phone: "#customer\\.phoneNumber",
  ssn: "#customer\\.ssn",
  createUsername: "#customer\\.username",
  createPassword: "#customer\\.password",
  confirmPassword: "#repeatedPassword",
  registerNewAccountButton: 'input[value="Register"]',
  headerPanel: "#headerPanel",
  accountsOverview: "a[href='overview.htm']",
  newAccountId: "a#newAccountId",
  accountId: 'a[href^="activity.htm?id="]',
  openNewAccount: 'a[href="openaccount.htm"]',
  selectAccountType: "select#type",
  openNewAccountButton: 'input[value="Open New Account"]',
  transferFunds: 'a[href="transfer.htm"]',
  amount: "input#amount",
  logOut: 'a[href="logout.htm"]',
  fromAccountId: "#fromAccountId",
  toAccountId: "#toAccountId",
  totalAmount: "tr td:nth-child(2) b",
  transferButton: 'input[value="Transfer"]',
  showResult: "#showResult",
  amountResult: "#amountResult",
  loanStatus: "td#loanStatus",
  requestLoan: 'a[href="requestloan.htm"]',
  downPayment: "#downPayment",
  applyNowButton: 'input[value="Apply Now"]',
  bill: {
    billPay: "a[href='billpay.htm']",
    payeeMame: 'input[name="payee.name"]',
    address: 'input[name="payee.address.street"]',
    city: 'input[name="payee.address.city"]',
    state: 'input[name="payee.address.state"]',
    zipCode: 'input[name="payee.address.zipCode"]',
    phone: 'input[name="payee.phoneNumber"]',
    account: 'input[name="payee.accountNumber"]',
    verifyAccount: 'input[name="verifyAccount"]',
    amount: 'input[name="amount"]',
    sendPaymentButton: 'input[value="Send Payment"]',
    billpayResult: "#billpayResult",
    confirmAmount: "#amount",
  },
  admin: {
    adminPage: 'li > a[href="admin.htm"]',
    initialBalance: "#initialBalance",
    minimumBalance: "#minimumBalance",
    submitButton: '.button[value="Submit"]',
  },
  updatePage: 'a[href="updateprofile.htm"]',
  leftPanel: "#leftPanel",
  welcomeText: ".smallText",
  updateButton: 'input.button[value="Update Profile"]',
  failTestElement: "#failTestElement",
};
